# Generated by Django 4.0.2 on 2022-03-05 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('avg_heartbeat', 'AVG_HEARTBEAT'), ('calories_consumed', 'CALORIES_CONSUMED'), ('sleep_hours', 'SLEEP_HOURS'), ('morning_pulse', 'MORNING_PULSE')], max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.metricsdata')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('avg_heartbeat', 'AVG_HEARTBEAT'), ('calories_consumed', 'CALORIES_CONSUMED'), ('sleep_hours', 'SLEEP_HOURS'), ('morning_pulse', 'MORNING_PULSE')], max_length=50)),
                ('value', models.DateField(default=django.utils.timezone.now)),
                ('p_value', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
