# Generated by Django 4.0.2 on 2022-02-14 12:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DataTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_data_type', models.CharField(choices=[('AVG_HEARTBEAT', 'avg_heartbeat'), ('CALORIES_CONSUMED', 'calories_consumed'), ('SLEEP_HOURS', 'sleep_hours'), ('MORNING_PULSE', 'morning_pulse')], max_length=50)),
                ('y_data_type', models.CharField(choices=[('AVG_HEARTBEAT', 'avg_heartbeat'), ('CALORIES_CONSUMED', 'calories_consumed'), ('SLEEP_HOURS', 'sleep_hours'), ('MORNING_PULSE', 'morning_pulse')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x_data', to='config.datadate')),
                ('y', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='y_data', to='config.datadate')),
            ],
        ),
    ]
