# Generated by Django 4.0.2 on 2022-02-14 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
