# Generated by Django 4.0.2 on 2022-02-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_datadate_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatypes',
            name='user',
        ),
    ]
